project_id = "mlpctpnqkqqzvwosrbeq"

[functions.analyze-template]
verify_jwt = true

[functions.process-cv]
verify_jwt = true

[functions.generate-cv-word]
verify_jwt = true

[functions.generate-cv-pdf]
verify_jwt = true
